name: Automatic Pull Request
on:
  push:
    branches:
      - Test
      
jobs:
  create-pull-requests:
    runs-on: macos-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        
      - name: Create Pull Request
        run: gh pr create -B main -H Test --title 'Merge Test into Main' --body 'Keep Main updated with Test'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
